### PR TITLE
Rewrite all the things!

### PR DESCRIPTION
**Pull request by jaywink**
Rewrite the old code using Django for the backend and Vue.js for the frontend.

Most of the templates have been transferred as is, as is much of the content. In addition to writing the internals, protocols has been added as a way to filter down on what nodes the network consists of. This is to allow expanding to collecting statistics from also non-Diaspora protocol metainfo documents (Mastodon/Friendica/Hubzilla stats endpoints at least planned).

Dropped a few of the graphs but can bring them back if demand. The JSON API's have been dropped in favour of a single GraphQL endpoint.

Live site, with old stats imported: https://dev.the-federation.info - this will become the new site once this is merged
GraphQL playground: https://dev.the-federation.info/graphql

Line by line review of this PR maybe not possible :P 

TODO before merge:
* [x] `shcli` to post daily statistics

### CODE REVIEW

**Comment by Zauberstuhl** [comment]
is it live on dev.the-federation.info ?

**Comment by jaywink** [comment]
Yes!

**Comment by Flaburgan** [comment]
Hi Jason! Awesome work!

I'm not sure the home page should say "5 protocols", to me "the federation" is about the project implementing [the federation protocol](https://github.com/diaspora/diaspora_federation) (currently mainly managed by diaspora*, but with friendica involved too). Saying there is more than one protocol defeats the point that it's a decentralized but unified social network, supported by several different projects all communicating together.

A part from that, it a really nice work!

**Comment by jaywink** [comment]
Hey @Flaburgan . Thanks for the feedback!

Basically the idea is to change the site from monitoring one protocol only to monitoring all the federated social protocols. This means including Mastodon, Pleroma, etc. It was one of the main reasons of this rewrite since extending the old code in this direction would have required too much painful changes.

It's true then we can't really say "unified one network". But we can for example show how many users can be reached by certain servers depending on which protocols they provide. And draw cool network graphs :)

**Comment by Flaburgan** [comment]
>It's true then we can't really say "unified one network". But we can for example show how many users can be reached by certain servers depending on which protocols they provide.

And that's a really nice thing. I'm just afraid that the name "the-federation" will be confusing for users who will not get what they are looking at. Is that one network where everyone shares? Previously the answer was yes, looks like it will soon be no, but the name is the same, and the website is confusing about that at the moment.

**Comment by jaywink** [comment]
I did remove the "ONE network" box, until we can really say that it is one network. This is unlikely to happen as we know not everyone will implement a single protocol. But even if everybody did implement a single protocol, whatever it is, the level of support based on features the platforms need vary so much that talking about a single network is not something that can be done easily. Even within the diaspora protocol network features are different and thus the "one network" idea is a bit flaky.

So, I would instead focus on mapping the whole fediverse, as many protocols and platforms as possible, and drawing a realistic picture of how many, what and most importantly, who can connect with who.

**Pull request merged**
